/**
 * @fileoverview Agent Definitions & Schemas
 * @module services/agentConfig
 * @description Defines the core system prompts, structured JSON schemas, and function tools
 * that govern the behavioral logic and capabilities of the AI Agent.
 */

// Define the master system prompt to establish the agent's persona, goals, and workflow constraints.
const SYSTEM_PROMPT = `You are an agentic recipe assistant. Your goal is to help users find recipes, present options, and generate a Google Doc for them.

WORKFLOW:
1. When a user asks for a recipe (e.g., "banana pudding"), use the 'search_web' tool to find recipe ideas if you lack internal knowledge.
2. Present 2-3 distinct options to the user using the 'options' array in your structured JSON response. Wait for the user to choose.
3. Once the user chooses an option, use the 'search_image' tool to find a suitable high-resolution image for the recipe.
4. Immediately use the 'create_recipe_doc' tool to generate the Google Document.
5. Return the resulting document URL in the 'doc_url' field of your structured JSON response and notify the user in the 'message' field.

Always adhere strictly to the provided JSON schema for your final response. Do not use markdown blocks.`;

// Define the strict JSON schema required for the AI's final output to the frontend.
const RESPONSE_FORMAT = {
  // Specify the response format type natively supported by the Universal Endpoint.
  type: "json_schema",
  json_schema: {
    name: "recipe_assistant_response",
    // Enforce strict schema compliance to guarantee parsability by the client.
    strict: true,
    schema: {
      type: "object",
      properties: {
        // The conversational text output aimed directly at the user.
        message: {
          type: "string",
          description: "Text response or question for the user explaining options or actions taken."
        },
        // An array of recipe options to populate the frontend selection UI.
        options: {
          type: "array",
          description: "A list of recipe options to show the user. Leave as an empty array if not currently proposing options.",
          items: {
            type: "object",
            properties: {
              title: { type: "string" },
              description: { type: "string" }
            },
            // Mandate both title and description for every provided option.
            required: ["title", "description"],
            // Prevent hallucinated properties outside of the defined scope.
            additionalProperties: false
          }
        },
        // The final artifact URL, populated only after successful generation.
        doc_url: {
          type: "string",
          description: "The Google Doc URL if a document was successfully created, otherwise an empty string."
        }
      },
      // Require all root-level properties to ensure a consistent object shape.
      required: ["message", "options", "doc_url"],
      additionalProperties: false
    }
  }
};

// Define the array of callable functions available to the Agent during execution.
const TOOLS = [
  {
    type: "function",
    function: {
      // The identifier used by the model to trigger the web search execution.
      name: "search_web",
      description: "Search Google for recipe ideas, ingredients, or cooking times.",
      parameters: {
        type: "object",
        properties: {
          // The semantic search string generated by the LLM.
          query: { type: "string" }
        },
        required: ["query"],
        additionalProperties: false
      }
    }
  },
  {
    type: "function",
    function: {
      // The identifier used by the model to trigger image retrieval.
      name: "search_image",
      description: "Search Google for a high-resolution food image of a recipe.",
      parameters: {
        type: "object",
        properties: {
          // The exact recipe title to query against the image index.
          title: { type: "string" }
        },
        required: ["title"],
        additionalProperties: false
      }
    }
  },
  {
    type: "function",
    function: {
      // The primary actuation tool allowing the agent to generate physical system artifacts (Google Docs).
      name: "create_recipe_doc",
      description: "Generate and save a Google Doc containing the fully detailed recipe.",
      parameters: {
        type: "object",
        properties: {
          title: { type: "string" },
          description: { type: "string" },
          prepTime: { type: "string" },
          cookTime: { type: "string" },
          servings: { type: "string" },
          ingredients: { type: "array", items: { type: "string" } },
          instructions: { type: "array", items: { type: "string" } },
          // Allows the model to inject the previously retrieved image URL directly into the document payload.
          imageUrl: { type: "string", description: "Optional URL of the recipe image. Pass empty string if none." }
        },
        // Mandate all schema fields to ensure the generated document is complete and formatted correctly.
        required: ["title", "description", "prepTime", "cookTime", "servings", "ingredients", "instructions", "imageUrl"],
        additionalProperties: false
      }
    }
  }
];
